displayName=Sounds of San Andreas
author=Donus
support=https://github.com/donusgits/Sounds-of-San-Andreas
description=Bring GTA:SA to Gielenor
tags=hit,sound,complete,gta,san,andreas
plugins=com.github.donus.sosa.SOSAPlugin