displayName=Custom Sound Overhaul
author=Donus
support=https://github.com/DapperMickie/odablock-sounds
description=Sound packs for your Runelite 
tags=hit,sound,complete,gta,san,andreas,minecraft
plugins=com.github.donus.cso.CSOPlugin